// Generated by https://quicktype.io

export interface GetContactosForCombo {
    id:       number;
    nombre:   string;
    mail:     string;
    telefono: string;
}

// Generated by https://quicktype.io

export interface GetMateriasForCombo {
    id:     number;
    nombre: string;
    curso:  string;
}
// Generated by https://quicktype.io

export interface GetEventosForCombo {
    id:          number;
    nombre:      string;
    descripcion: string;
    fecha:       string;
}

// Generated by https://quicktype.io

export interface GetContactosForCombo {
    id:       number;
    nombre:   string;
    mail:     string;
    telefono: string;
}

// Generated by https://quicktype.io

export interface GetMateriasPorCurso {
    id:     number;
    nombre: string;
    curso:  string;
}

// Generated by https://quicktype.io

export interface GetIntegrantesPorCurso {
    id:         number;
    materia:    Materia;
    id_Materia: number;
    usuario:    Usuario;
    id_Usuario: number;
}

export interface Materia {
    id:     number;
    nombre: string;
    curso:  string;
}

export interface Usuario {
    id:       number;
    nombre:   string;
    apellido: string;
    perfil:   string;
    mail:     string;
    activo:   boolean;
}
// Generated by https://quicktype.io

export interface GetAsistenciaByID {
    id:         number;
    alumno:     Alumno;
    id_Alumno:  number;
    materia:    Materia;
    id_Materia: number;
    fecha:      string;
    presente:   boolean;
}

export interface Alumno {
    id:       number;
    nombre:   string;
    apellido: string;
    perfil:   string;
    mail:     string;
    activo:   boolean;
}

export interface Materia {
    id:     number;
    nombre: string;
    curso:  string;
}
